version: '3'

services:
  webserver:
    image: apache/airflow:2.0.0
    container_name: airflow-webserver
    restart: on-failure
    depends_on:
      - scheduler
    ports:
      - 8080:8080
    volumes:
      - ./opt/airflow:/opt/airflow
    # command: db init # Use fist time only
    command: webserver # Using with docker-compose up after exec `db init`
  
  scheduler:
    image: apache/airflow:2.0.0
    container_name: airflow-scheduler
    restart: always
    volumes:
      - ./opt/airflow:/opt/airflow
    command: scheduler