version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    ports:
        - 3306:3306
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./conf:/etc/mysql/conf.d
  
  scheduler:
    image: apache/airflow:2.0.0
    container_name: airflow-scheduler
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    command: scheduler

  webserver:
    image: apache/airflow:2.0.0
    container_name: airflow-webserver
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - scheduler
      - mysql
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    # command: db init # Use fist time only
    command: webserver # Using with docker-compose up after exec `db init`